### ISSUE TITLE
Question: How do you test this library?

### ISSUE THREAD

**Issue by pboyer** [gradientspace/geometry3Sharp#1]
:) Feel free to close this - just curious what your strategy is.

**Comment by rms80** [comment]
excellent question! TBH the main testing is by my daily usage of it. However I have written some tests of core classes/algorithms in the Demos project:

https://github.com/gradientspace/geometry3SharpDemos

Which I do manually run once in a while to check for regressions. Nothing is automated at this point.

(I still think of this more as a personal project then a "component" I am providing. However I had to make it public for IP/contract reasons.)

**Comment by rms80** [comment]
Oh, also many of the parts that are not 3D-mesh-related (ie like the distance functions, etc) are ports from the C++ WildMagic and GTEngine libraries (geometric tools.com) which are rigorously tested.

**Comment by pboyer** [comment]
OK, cool. Thanks for the details. :D Good luck!
