### ISSUE TITLE
Creating an arc from 3 or more points in 3D

### ISSUE THREAD

**Issue by riegaz** [gradientspace/geometry3Sharp#102]
Is there a function that allows me to create an arc from 3 or more points in 3D?

Maybe one of the following functions?

culptMoveDeformation, ArcLengthSoftTranslation, SampledArcLengthParam

Basically, I do have points following the surface of an triaxial ellipsoid and I would like to create a fitting arc in 3D from them.

Any ideas are welcome.

**Comment by rms80** [comment]
sorry, there is not such a function
