### ISSUE TITLE
Why there no Matrix 4x4?

### ISSUE THREAD

**Issue by WangWeiQiang230** [gradientspace/geometry3Sharp#107]

**Comment by SirKnightTG** [comment]
Yes, this is a very odd omission.

Also missing the Frustum class.

**Comment by visose** [comment]
I'm probably wrong, but if you're working in world space, Frame3f will give you most transformations that you need, more efficiently than using matrices. Matrix4x4's common use on the GPU for things like perspective projection is something out of the scope of this library.
