### ISSUE TITLE
Mesh from point cloud without normals

### ISSUE THREAD

**Issue by petrasvestartas** [gradientspace/geometry3Sharp#109]
Hi,

I tried to follow the tutorial from this page:
http://www.gradientspace.com/tutorials/2018/9/14/point-set-fast-winding

But I did not succeeded, is it possible to get a dummy tutorial with fully working example code when the user only adds a point set for instance cube corners?
I understand that it will approximate a sphere, but would really like if you could give me an example how to reconstruct a mesh from a set of points:

p0 -1, -1, -1
p1 1, -1, -1
p2 1, 1, -1
p3 -1, 1, -1
p4 -1, -1, 1
p5 1, -1, 1
p6 1, 1, 1
p7 -1, 1, 1

**Comment by mfdeveloper** [comment]
+1 

I've the same doubt. Did you solve this @petrasvestartas ? I'm trying to use Surface Reconstruction with this library, but I'm so confuse how to do that 😢

**Comment by petrasvestartas** [comment]
No, because geometry3sharp does not have normal estimation.

I ended up using Open3D C++ library that I managed to PInvoke to .NET:
https://vimeo.com/500897142

This is working in Rhino, Grasshopper. 

For now I release only C++ version as Rhino plugin.
But in coming months I am planning to publish C# wrapper as well:
https://www.food4rhino.com/app/cockroach

**Comment by mfdeveloper** [comment]
It's amazing @petrasvestartas ! Awesome work 😮 

So, Can I use this plugin "decoupled" from Rhino? In any other 3D software/library ?

I've using a paid .NET C# library called [AB4D](https://www.ab4d.com/), and I'm searching for a generic library that not use any specific 3D library. Just consume a `.txt, .obj, .ply` point cloud file and generate another file, stream or string content Mesh file using Surface Reconstruction algorithm.

Do you have any `.cs` file in any github repository writted in `C#` that you can share with us, please? It's not necessary be a nuget package now. Just  `.cs` files are enough for while.

Thank you sooo much for your response and link references!!
