### ISSUE TITLE
Normalized Vector3d is not normalized

### ISSUE THREAD

**Issue by brianoc** [gradientspace/geometry3Sharp#11]
Hi, first of all wanted to say thanks for the library, it is very broad and useful. Really enjoying using it. I did notice one minor issue while using Unity that I thought I'd mention. After I normalized a Vector3d it still returned false when calling IsNormalized.

This is not a priority for me as I changed the check of IsNormalized to compare against MathUtil.ZeroTolerancef rather than MathUtil.ZeroTolerance and it is working fine for me although I haven't checked thoroughly if this fixes all cases.

Here are one set of values that reproduced the case,

Vector3d with x, y, z values,
-.90034962
.37379742
-.22281371

gives (x * x + y * y + z * z) of 
.9999998987967649

and Math.Abs( (x * x + y * y + z * z) - 1) of
0.0000001012032351

which is greater than 1e-08.

Cheers,
Brian :)

**Comment by rms80** [comment]
Sorry, these tolerances are basically just copied from WildMagic/GTEngine, not the first time I have seen one be off in some cases.

But, can you tell me the values of the original vector that you passed in to Normalize()? I would like to write an exhaustive search to try to find these extreme values...

**Comment by brianoc** [comment]
Well, I actually got it from a UnityEngine.Vector3 which uses floats rather than doubles (but is otherwise what you would expect). I didn't document the original values but another case that gives this case has the values,

-0.712443
0.1036605
-0.6940313

When cast to a Vector3d these become,
-0.712442994117737
0.103660546243191
-0.694031298160553

Is there anything else I can get you?

**Comment by rms80** [comment]
right, ok, I wondered if was this, I have run into this myself. But, I don't think changing the tolerance is the correct thing to do (for the library - you can do whatever you want =)

"normalized float-vector is not normalized after casting to doubles" is, basically, correct behavior, as far as floating-point math is concerned. If you allow this larger tolerance for what is considered 'normalized', then all the tolerances in downstream algorithms (ie where you might be doing some op w/ that less-normalized vector) also need to be increased.

This is an unfortunate side-effect of C# not having proper generics support for POD types. I can't easily write float/double versions of everything without fully duplicating the code. But if you want to use the double version w/ float inputs, then a bit of extra work - like re-normalization - is unavoidable.

**Comment by brianoc** [comment]
Ah, sorry I wasn't clear. After creating the g3.Vector3d from the UnityEngine.Vector3 input I did call Normalize() on the g3.Vector3d. It still returns IsNormalized as false (when comparing to the double MathUtil.ZeroTolerance), even immediately after calling Normalize() (the function, not just the Normalized property).

I agree that assuming a normalized float V3 cast to a double V3 is still normalized in doubles would be dangerous. Also, that's a good point about all downstream tolerances being affected too. I know what you mean about Generics not being specific enough, that is a pity :(

**Comment by CBenghi** [comment]
@brianoc,

because I'm thinking to use this amazing library in production, I'm having a look at old issues and I've tried to reproduce the problem you have with the following code:

```csharp
Console.WriteLine("Testing normalization.");
var v = new Vector3d(-0.712443, 0.1036605, -0.6940313);
Console.WriteLine($"Initial vector; {v} IsNormalized: {v.IsNormalized}");
v.Normalize();
Console.WriteLine($"After normalization; {v} IsNormalized: {v.IsNormalized}");
if (!v.IsNormalized)
	throw new Exception("Normalization failure.");
```

Currently, the library seems to work as expected. 
Were you running a different comparison than the standard `v.IsNormalized`? 
Can you close the issue if this is solved?

**Comment by brianoc** [comment]
Hi @CBenghi ,

I'm sorry but I don't have access to the project that was running this library anymore so I can't re run the tests. I believe it was calling IsNormalized but since you can't reproduce it and it's clearly not a problem for me anymore I think closing the issues is the best solution.

Thanks for your help and have a good day!
