### ISSUE TITLE
Godot Mesh builds dmesh with inverted Triangles.

### ISSUE THREAD

**Issue by Blargstomp404** [gradientspace/geometry3Sharp#131]
I was able to make a dmesh with godot mesh arrays, it pass the validity check, however the dmesh faces are inverted. Do you have a way to reverse the triangle order or flip the normals?

**Comment by Blargstomp404** [comment]
Was able to reverse the triangles indices, faces are pointing in the right direction now. Had to make groups of Index3i and the move the end ints around. "_tempTri.Add(new Index3i(temp3,temp2,temp1));"

**Comment by rms80** [comment]
DMesh3.ReverseOrientation() does this

**Comment by Blargstomp404** [comment]
Oh awesome, thank you for this awesome tool.
