### ISSUE TITLE
[Question] How do can i rotate my DMesh3?

### ISSUE THREAD

**Issue by FloP93** [gradientspace/geometry3Sharp#140]
I am sorry, if this is the wrong place but i couldnt find anything about it, but what would be the best and most performant way to rotate my DMesh3? 
For example i want to rotate the bunny 90 degree around the x, y or z axis. 
If there are some documents or tutorials you can suggest me to help me with that i would appreciate it.

I think i can use Frame3f for that, but how do i combine my DMesh3 with the Frame3f?

**Comment by rms80** [comment]
use the MeshTransforms class

**Comment by FloP93** [comment]
Oh, i missed that class. Thank you => closed.
