### ISSUE TITLE
Is there a way to scale the model in inches?

### ISSUE THREAD

**Issue by Blargstomp404** [gradientspace/geometry3Sharp#144]
I have a project that is an figurine editor with different options for scale for 3d printing. It looks like there is a function for it, but I'm still new with geometry3Sharp and need a light help setting it up.

**Comment by rms80** [comment]
There are no units in the library. It's up to you to define what "1.0" means. If you decide that is meters, and you want to convert to inches, then you scale by 39.3701. 

MeshTransforms.cs has various functions for scaling meshes.
