### ISSUE TITLE
Custom (simple) reducer?

### ISSUE THREAD

**Issue by eidng8** [gradientspace/geometry3Sharp#15]
I'm working on a plane mesh. 128-cell square rectangle, with cell also squares. I build the mesh procedurally, using DMesh3. Upon built, I want to reduce the triangle count, by merging adjacent cells with same  height (Y axis). Looking at thr reducer, it doesn't seem operable on such simple case. Just want to confirm am I correct?

**Comment by rms80** [comment]
The Reducer should decimate coplanar triangles before it simplifies anything else. However, there is no setting currently that would prevent it from also decimating some of the non-coplanar faces.

You could try just using DMesh3.CollapseEdge directly, and copy the code out of Reducer that checks for face-flips before collapsing. 

alternately you could try to hack it into Reducer. The internal function creates_flip_or_invalid() is a good place. If you return false from there, the collapse is prevented, and it already computes the face normals. Just normalize ncur and nnew, and return false if the dot-product sign is not within epsilon of 1.

**Comment by eidng8** [comment]
Yes, exactly what I'm thinking. Just to confirm if I get it right.

My thought is, Reducer has an obvious pipeline-like flow. Which can be generalized to a base class of all reduce features. However, too much flexibility isn't Good here. As we have two possible  way of doing this:

1. Hack and slash inside current Reducer class, and split it into general steps;
2. Or enhance Constraint classes to provide interoperability.

Worse, we may need both.

Any suggestion?

**Comment by rms80** [comment]
you could solve this w/ the current Constraints. If you add a no-collapse edge constraint on the right edges of the grid, it will only simplify in the flat regions. 

I'm not sure what kind of 'general steps' you mean. It would be straightforward to add in (for example) configurable Func<>'s that make it possible to implement additional constraints inside CollapseEdge(). To implement a different reduce policy (ie ordering, stopping constraint, etc) you could override DoReduce(). 

There is really not much to the Reducer class, most of the code is to implement the QEM metric/queue and basic geometric constraints (don't break mesh, don't flip edges, etc).
