### ISSUE TITLE
How can we visually create meshes?

### ISSUE THREAD

**Issue by webyonetici** [gradientspace/geometry3Sharp#18]
How can we visually create meshes?

**Comment by rms80** [comment]
use other software? =) 
This is a library for mesh data structures. It does not deal with visualization at all. If you want to view a mesh, I would recommend Autodesk Meshmixer. It's pretty good for making meshes, too.

**Comment by Evil-Spirit** [comment]
I am using Unity3d. Perfect choice.

**Comment by Evil-Spirit** [comment]
@rms80 meshmixer calculates wrong normals for me:
![autodesk meshmixer - notecadexport 1 stl 2017-11-24 14 40 50](https://user-images.githubusercontent.com/1980537/33200038-849eb2a4-d125-11e7-9ee2-3a1e59da4238.png)

**Comment by rms80** [comment]
I don't have anything to do with meshmixer anymore, you would have to contact their support for problems. However, also, this is what vertex normals look like on a low-poly mesh. try switching to face normals (hold down spacebar)

**Comment by Evil-Spirit** [comment]
@rms80 
Thanks! But can you tell me: why are all the folks use STL - it is not support vertex normals and modles can't look line original. Do you know any alternatives? I am also [CAD Developer](http://notecad.xyz)

**Comment by rms80** [comment]
People in CAD use STL mainly because CAM software mostly only reads STL. OBJ and AMF formats has some support in 3D printing software, but CNC software is mostly only taking STL. 

Vertex normals have no effect on the actual shape of the mesh, so they are misleading in any kind of engineering or manufacturing context.

**Comment by webyonetici** [comment]
Thank you for your interest.
Is there a source code that I can visually design as a mesh?
(especially C#)
