### ISSUE TITLE
Remesher Example

### ISSUE THREAD

**Issue by petrasvestartas** [gradientspace/geometry3Sharp#2]
Hi,

I would to ask if it is possible to get a remesher example?

I am totally new to this library. And would like to create a simple mesh geometry and remesh as a test.

Would you be kind to show how to do this?

**Comment by rms80** [comment]
There is some (disorganized) sample code in the [geometry3SharpDemos](https://github.com/gradientspace/geometry3SharpDemos) project. 

Here is some testing code for the Remesher that might point you in the right direction:

https://github.com/gradientspace/geometry3SharpDemos/blob/master/geometry3Test/test_Remesher.cs

**Comment by alexhackbai** [comment]
I would to ask if it is possible to mesh simplfication example?
thank you

**Comment by rms80** [comment]
There are tutorials on these topics now:
http://www.gradientspace.com/tutorials/2017/8/30/mesh-simplification
http://www.gradientspace.com/tutorials/2018/7/5/remeshing-and-constraints
