### ISSUE TITLE
Can I use this library

### ISSUE THREAD

**Issue by Evil-Spirit** [gradientspace/geometry3Sharp#22]
I am developing cad system: http://notecad.xyz.
Can I use this library in this project (I mean license)?

**Comment by rms80** [comment]
yes, the license is boost license: https://opensource.org/licenses/BSL-1.0

I appreciate if you mention that you are using the library in your about box / etc, but this is not legally required by the license.

**Comment by Evil-Spirit** [comment]
@rms80 thank you for you answer and library contribution
