### ISSUE TITLE
MeshPlaneCut bug?

### ISSUE THREAD

**Issue by nyblomper** [gradientspace/geometry3Sharp#23]
Hi, thanks for sharing this lib.

I am trying to procedurally create some bevels on a cube with the MeshPlaneCut class:

// Unity code below:
var cube = GameObject.CreatePrimitive(PrimitiveType.Cube);

        var mesh = cube.GetComponent<MeshFilter>().sharedMesh;

        var dMesh = mesh.ToDMesh3();

        MonoBehaviour.DestroyImmediate(cube);

        double dist = 0.45;

        var cutDirs = new List<Vector3d> {
            new Vector3d(dist, dist, 0),
            new Vector3d(dist, -dist, 0),
            new Vector3d(-dist, dist, 0),
            new Vector3d(-dist, -dist, 0),
            new Vector3d(0, dist, dist),
            new Vector3d(0, dist, -dist),
            new Vector3d(0, -dist, dist),
            new Vector3d(0, -dist, -dist),
            new Vector3d(dist, 0, dist),
            new Vector3d(dist, 0, -dist),
            new Vector3d(-dist, 0, dist),
            new Vector3d(-dist, 0, -dist),
        };

        foreach (var cutDir in cutDirs) {
            var cut = new MeshPlaneCut(dMesh, cutDir, cutDir.Normalized);
            cut.Cut();
            cut.FillHoles();
        }

        mesh = dMesh.ToUnityMesh();

        var go = new GameObject("result");

        var mf = go.AddComponent<MeshFilter>();
        mf.sharedMesh = mesh;

        var renderer = go.AddComponent<MeshRenderer>();
        var material = new Material(Shader.Find("Standard"));
        material.color = Color.red;
        renderer.material = material;

The problem is that the holes are not filled and there the plane cutter reports that there are only CutSpans and no CutLoops.
Is this a bug or intended behaviour?

Thanks!

Oh, right here is the code for ToUnityMesh() and ToDMesh3():

public static DMesh3 ToDMesh3(this Mesh mesh) {
        DMesh3 result = new DMesh3(bWantNormals: true, bWantUVs: true);

        var verts = mesh.vertices;
        var tris = mesh.triangles;
        var normals = mesh.normals;

        for (int i = 0; i < verts.Length; i++) {
            result.AppendVertex((Vector3d) verts[i]);
            result.SetVertexNormal(i, normals[i]);
        }

        for (int i = 0; i < tris.Length; i += 3) {
            result.AppendTriangle(tris[i], tris[i+1], tris[i+2]);
        }

        return result;
    }

    public static Mesh ToUnityMesh(this DMesh3 dm) {
        var result = new Mesh();

        List<Vector3> vertices = new List<Vector3>();
        List<int> triangles = new List<int>();
        List<Vector3> normals = new List<Vector3>();
        List<Vector2> uvs = new List<Vector2>();

        int[] mapV = new int[dm.MaxVertexID];

        int nAccumCountV = 0;
        // write vertices for this mesh
        foreach (int vertId in dm.VertexIndices()) {
            mapV[vertId] = nAccumCountV++;
            Vector3d vert = dm.GetVertex(vertId);
            vertices.Add((Vector3) vert);
            uvs.Add(dm.GetVertexUV(vertId));
            normals.Add(dm.GetVertexNormal(vertId));
        }

        foreach (var triIndex in dm.TriangleIndices()) {
            var tri = dm.GetTriangle(triIndex);
            triangles.Add(mapV[tri.a]);
            triangles.Add(mapV[tri.b]);
            triangles.Add(mapV[tri.c]);
        }

        result.vertices = vertices.ToArray();
        result.normals = normals.ToArray();
        result.triangles = triangles.ToArray();
        result.uv = uvs.ToArray();

        return result;
    }

**Comment by rms80** [comment]
I have not tried your code, but from what you have described, my guess is that the unity cube is actually 6 separate planes (almost certain about this). The plane-cut can work on that, but the result is still separate mesh patches. To do a hole-fill, the cube faces need to be welded along the borders.

An easy way to do this is to add the unity Mesh vertices to a Dictionary, where you assign a new vertex id only if the vertex is not already in the dictionary (my Vertex3d can be used as a Dictionary key). Then your mapV will map some input-triangle vertices to the same output vertex, and the result will be welded together.

This will break UVs, though. If you need to preserve UVs through this...that is more complicated.

**Comment by nyblomper** [comment]
Ahh, right. This must be the case since all the sides of the Unity cube have separate normals. So it should be possible to create a loop out of those CutSpans I guess. 
I'll probably just go with your solution and always process the mesh as "closed". Then I'll break it up to create separate faces if needed.
Thanks!

**Comment by nyblomper** [comment]
It works :)

Ran into some numerical issues during cutting, but nothing that couldn't been fixed with small offsets.

Here is the code for creating the merged mesh if anyone is interested:

    public static DMesh3 ToDMesh3Merged(this Mesh mesh) {
        DMesh3 result = new DMesh3(bWantNormals: false);

        var verts = mesh.vertices;
        var tris = mesh.triangles;

        Dictionary<Vector3d, int> vertexHashToUnityVertexIndex = new Dictionary<Vector3d, int>();

        int[] unityVertexIndexToDMeshVertexIndex = new int[verts.Length];

        for (int i = 0; i < verts.Length; i++) {
            var vert = (Vector3d) verts[i];

            if (vertexHashToUnityVertexIndex.ContainsKey(vert)) {
                var mergedUnityVertexIndex = vertexHashToUnityVertexIndex[vert];
                unityVertexIndexToDMeshVertexIndex[i] = unityVertexIndexToDMeshVertexIndex[mergedUnityVertexIndex];
            } else {
                int vertId = result.AppendVertex(
                    new NewVertexInfo {
                        v = vert,
                    }
                );
                vertexHashToUnityVertexIndex[vert] = i;
                unityVertexIndexToDMeshVertexIndex[i] = vertId;
            }
        }

        for (int i = 0; i < tris.Length; i += 3) {
            result.AppendTriangle(
                unityVertexIndexToDMeshVertexIndex[tris[i]], 
                unityVertexIndexToDMeshVertexIndex[tris[i+1]], 
                unityVertexIndexToDMeshVertexIndex[tris[i+2]]);
        }

        return result;
    }


Also, here is some code to split all vertices, if you want to do some flat-shaded stuff:

public static DMesh3 ToSplittedDMesh3(this DMesh3 dm) {

        DMesh3 result = new DMesh3(bWantNormals: false);

        foreach (var triIndex in dm.TriangleIndices()) {
            var tri = dm.GetTriangle(triIndex);

            var a = result.AppendVertex(dm.GetVertex(tri.a));
            var b = result.AppendVertex(dm.GetVertex(tri.b));
            var c = result.AppendVertex(dm.GetVertex(tri.c));
                
            result.AppendTriangle(a, b, c);
        }

        return result;

    }
