### ISSUE TITLE
Raise/Throw error on triangles added more than once?

### ISSUE THREAD

**Issue by CodeDoes** [gradientspace/geometry3Sharp#30]
```
// [RMS] What to do here? We definitely do not want to add a duplicate triangle!!
//   But is silently ignoring the right thing to do?
```
I'm still figuring my way through the library. But I'd appreciate the library showing my when I did a wrong. So that something doesn't bite me in the ass later .

**Comment by rms80** [comment]
The comment is slightly out-of-date, in that you can now configure this behavior (look at AddTriangleFailBehaviors). The default for duplicate triangles is still to discard them, though.

if you throw in this situation, then you will not be able to load a significant percentage of real-world meshes (DMesh3Builder is used by the mesh loaders). This is not practical for a mesh processing library, we have to be able to load these files.

But, I can add a throw option to AddTriangleFailBehaviors, if you really think you want it.

**Comment by ClikCode** [comment]
Nah. Maybe change comment to reflect the changes? Meshes are almost never perfect.
