### ISSUE TITLE
Do you have the method Mesh Boolean Split? 

### ISSUE THREAD

**Issue by samyuchao** [gradientspace/geometry3Sharp#31]
Like this...
![image](https://user-images.githubusercontent.com/10825626/35660972-27571a54-074a-11e8-934d-f4e6c15f521a.png)

**Comment by Evil-Spirit** [comment]
Please, look into this http://www.gradientspace.com/tutorials/2017/11/21/signed-distance-fields-tutorial

**Comment by samyuchao** [comment]
Thank you! That looks very similar.  But it seems they use the different algorithms.  
g3sharp use the SFD algorithm, it looks the triangles have been reconstructed. 
Do you know what algorithm does Rhino use?  it looks the triangles is not changed.

**Comment by Evil-Spirit** [comment]
Rhino probably uses B-Reps with NURBS Boolean operations. If you need simplier solutions, you can search for triangle mesh boolean operations library (something like CGAL).

**Comment by samyuchao** [comment]
Do you know this project?  It seems a similar C# project processing mesh.
https://github.com/DesignEngrLab

**Comment by samyuchao** [comment]
https://github.com/DesignEngrLab/TVGL

**Comment by rms80** [comment]
currently g3sharp does not have mesh booleans. Looking at this TVGL library, it seems like they also have not implemented mesh booleans yet (unless I missed it). 

Mesh booleans are very difficult to implement reliably. All the (reasonably-good) implementations I know of are in C++. The one in libigl (https://github.com/libigl/libigl) is the best, but it depends on CGAL.

**Comment by samyuchao** [comment]
Thank you! I try to look at it.
