### ISSUE TITLE
Tube generator capping problem

### ISSUE THREAD

**Issue by sandord** [gradientspace/geometry3Sharp#32]
I think there's a bug in the tube generator capping because it caps in the following incorrect way:

![image](https://user-images.githubusercontent.com/260737/35805691-1f665202-0a7d-11e8-8ba3-67314e2c5c05.png)

Also, the incorrect (red) vertex color is typical, although it doesn't happen on the far end side.

    var profile = ... a semicircle
    
    var path = Polygon2d
        .MakeCircle(innerRadius, steps)
        .Vertices.Select(n => new Vector3d(n.x, 0, n.y))
        .Take((int)(steps * 0.88f))
        .ToArray();
    
    var tubeGenerator = new TubeGenerator
    {
        Polygon = profile,
        Vertices = pathVertices,
        Capped = true
    };

**Comment by sandord** [comment]
These are the profile meshes:

     [0] {0,02300000 -0,50000000}
     [1] {0,03100000 -0,58900000}
     [2] {0,04700000 -0,71000000}
     [3] {0,06500000 -0,82600000}
     [4] {0,08600000 -0,93500000}
     [5] {0,11000000 -1,03600000}
     [6] {0,13600000 -1,12900000}
     [7] {0,16400000 -1,21300000}
     [8] {0,19400000 -1,28700000}
     [9] {0,22600000 -1,35100000}
    [10] {0,25900000 -1,40400000}
    [11] {0,29300000 -1,44500000}
    [12] {0,32800000 -1,47500000}
    [13] {0,36300000 -1,49300000}
    [14] {0,39900000 -1,50000000}
    [15] {0,47100000 -1,49300000}
    [16] {0,54200000 -1,47500000}
    [17] {0,61200000 -1,44500000}
    [18] {0,68000000 -1,40400000}
    [19] {0,74600000 -1,35100000}
    [20] {0,80900000 -1,28700000}
    [21] {0,86900000 -1,21300000}
    [22] {0,92500000 -1,12900000}
    [23] {0,97700000 -1,03600000}
    [24] {1,02500000 -0,93500000}
    [25] {1,06700000 -0,82600000}
    [26] {1,10400000 -0,71000000}
    [27] {1,13500000 -0,58900000}
    [28] {1,15300000 -0,50000000}

**Comment by sandord** [comment]
When inspecting the mesh, this caught my eye:

![image](https://user-images.githubusercontent.com/260737/35806212-0aec4dc0-0a7f-11e8-8384-e10a46e93880.png)

These two vectors shouldn't have `y=0`, the whole mesh shouldn't be in that range.

Debugging the `TubeGenerator` class, I found that the `4890` and `4891` indices are exactly between the `nBottomC` and `nStartB` variables passed in `append_disc(Slices, nBottomC, nStartB, true, Clockwise, ref ti);`

**Comment by rms80** [comment]
Well, the caps are made by creating a triangle fan around a "center" vertex, and currently that center vertex is defined as the start/end points of the path curve, projected into the start/end Frames. So, if the 2D projection of those points is not inside your profile polygon, then the fan will be nonsense. From what I can see your profile doesn't contain the origin, so that's my guess for what is going wrong here...

To cap an arbitrary polygon, it has to be triangulated, and I don't have a great arbitrary-polygon-triangulator yet. TriangulatedPolygonGenerator may work. 

Your profiles look like they are convex, in which case the fan triangulation would work if the center point ended up inside the profile. If you translate your profile, it might resolve it. I will try to add in the ability to either specify or re-calculate a better cap center-point...

**Comment by sandord** [comment]
Thanks, that's really clarifying.

My profiles are indeed convex. I actually had tried translating them to have origin inside but then my normals in the mesh became all wrong, I'm stacking several closed loop tubes and the environment map is restarting at each tube.

I've tried translating y-s of the normals to compensate for the translated profile. I'm pretty sure this is a very naive approach, I don't have much knowledge of how normals work. While the outcome looks quite okay (environment map not restarting) there's something off with the normals and I can't figure out exactly what.

**Comment by rms80** [comment]
Added TubeGenerator.CapCenter, if you set this to centroid of your polygons then you don't have to translate them.

Normals aren't really meant to be translated - they represent directions, so "translating" the values in a normal means pointing them in some other direction. 

The generator is setting the normals as if the profile were a circle, which is wrong, and extra-wrong if your profile is shifted from the origin. Calculating 'correct' normals for an arbitrary profile is somewhat difficult. I would suggest instead calling MeshNormals.QuickCompute() on the output DMesh3, that will re-calculate averaged vertex normals.

**Comment by sandord** [comment]
Thank you so much, your help has been very helpful and clarifying.

The new `CapCenter` works really well.
