### ISSUE TITLE
Do you have any idea to create this kind model with geometry3Sharp library?

### ISSUE THREAD

**Issue by samyuchao** [gradientspace/geometry3Sharp#33]
It seems use some points and their data on borehole, and then in spatial interpolation construct the signed distance filed, and then create the mesh?
![1](https://user-images.githubusercontent.com/10825626/36015566-f3ee6ea4-0da9-11e8-8d91-1f0df5a67389.png)

https://sketchfab.com/ctech/models?cursor=cD0yMDE2LTA5LTA4KzE2JTNBMzMlM0EwNC44NzE3MzYmcj0x

**Comment by samyuchao** [comment]
https://sketchfab.com/models/107154d103bd4b4f8e847546fff2d494

**Comment by samyuchao** [comment]
and this one. https://sketchfab.com/models/107154d103bd4b4f8e847546fff2d494

**Comment by rms80** [comment]
This is one way: http://mesh.brown.edu/DGP/pdfs/Carr-sg2001.pdf

This mode: https://sketchfab.com/models/c44fbdb8feed4f0393df4814b7772b10 mentions the different techniques - "FastRBF" is that paper (they started a company: fastrbf.com)

The WildMagic library has a radial basis function interpolation implementation: https://geometrictools.com/

it is not that difficult to implement, really - you just solve a matrix. That gives you a function F(x,y,z), which you can plug into a marching cubes mesher, which I do have in g3sharp. 

I have a sparse matrix solver (iterative, conjugate gradient) which would work with RBF setups that use locally-supported basis functions. For global support (like FastRBF), you need to solve a dense matrix, which only works up to a few thousand points. After that you need fast-multipole-methods (FMM), which is what FastRBF sells.

**Comment by samyuchao** [comment]
It seems MarchingCubes can be used to create the model.  Is there any function can be  used to create DMesh3 with only some points?

**Comment by rms80** [comment]
no, not in g3sharp currently.

**Comment by samyuchao** [comment]
so I have to create a mesh firstly, then convert to DMesh3 object,
