### ISSUE TITLE
Order of operations for MeshSignedDistanceGrid / MarchingCubes

### ISSUE THREAD

**Issue by soraryu** [gradientspace/geometry3Sharp#34]
After some trial and error I figured out that for e.g. subtracting a sphere from a bunny one way is to
1) reverse the sphere with ReverseOrientation
2) use a MeshEditor to append the bunny and the sphere
3) run both through a MeshSignedDistanceGrid
4) run MarchingCubes on that sdf.

That means that whenever I want to move a piece inside of a more complex operation (say, I want to move the sphere around that gets subtracted), I'll have to regenerate the mesh and the SDFs for everything. Is there a way to combine different SDFs together to speed things up? What I'd want to do is this order:
1) have a ton of operator meshes (reversed or not reversed)
2) generate SDFs for all of them
3) combine SDFs into one SDF
4) run MarchingCubes on that combined SDF

And whenever something changes:
1) recalculate only the SDF of the changed mesh - if it's only a translation, it shouldn't even be necessary to compute the SDF again, it can just be moved around (change of origin)
2) combine SDFs again
3) run MarchingCubes.

Am I just missing something? If not, consider this a feature request :)

**Comment by rms80** [comment]
Yes, that makes sense. I wrote a tutorial about how to do this: http://www.gradientspace.com/tutorials/2018/2/20/implicit-surface-modeling
