### ISSUE TITLE
Optionally write the material to a string instead of a file

### ISSUE THREAD

**Issue by sandord** [gradientspace/geometry3Sharp#36]
Currently, the OBJWriter supports writing the material only to a file path. Some of us might need the material in memory however so it would be nice if we could write it to a string or something.

I'm currently hacking around this by writing to a temporary file and subsequently reading it into a string. This is of course very inefficient.

**Comment by rms80** [comment]
Ok, I added StandardMeshWriter.OpenStreamF and CloseStreamF. By default these open a file stream and Dispose() it. If you return your own MemoryStreams instead, and don't Dispose() in CloseStreamF, you should be able to do what you are asking for.

OpenStreamF is called for the material in OBJWriter, however you will have to differentiate which stream to return based on the filename that is passed (eg using EndsWith(".mtl"))
