### ISSUE TITLE
Cutting, stretching and boolean operation with 3d meshes

### ISSUE THREAD

**Issue by VadymIgnatiev** [gradientspace/geometry3Sharp#41]
I am new in your library, but it very interesting me for my current unity3d project, so now I am trying evaluated ability to use geometry3Sharp. How can I implement cutting, stretching and boolean operation with 3d meshes using geometry3Sharp? For example, I want to subtract one shape from another, is this possible? Maybe do you have examples or you can advise me class or method name which helps me. Thanks.

**Comment by rms80** [comment]
There are some tutorials here: http://www.gradientspace.com/tutorial-index/

There are no mesh booleans, but there is a tutorial for converting meshes to SDFs, doing booleans, and converting back to mesh.

For stretching, you could try LaplacianMeshDeformer. There are lots of spatial deformations you could implement just by moving the vertices, ie DMesh3.SetVertex()

For cutting, there is MeshPlaneCut but it only has an extremely basic hole-filler, probably not what you are imagining. I have more robust options but they are not open-source, I make them available as part of development consulting.
