### ISSUE TITLE
CurveUtils.ArcLength overload bug

### ISSUE THREAD

**Issue by sandord** [gradientspace/geometry3Sharp#42]
In the following overload, `prev` is never updated so the result of the method is incorrect:

https://github.com/gradientspace/geometry3Sharp/blob/2502714afc50ccf24741615eebb0964219b6a260/curve/CurveUtils.cs#L40

**Comment by rms80** [comment]
yikes, thanks. Have checked in fix. (I will try to get to your tube generator PR today)
