### ISSUE TITLE
MeshIsoCurves.compute_full crashes with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by benetnash** [gradientspace/geometry3Sharp#44]
Hi!
I have stl which crashes slicer. Issue in with 
[MeshIsoCurves](https://github.com/gradientspace/geometry3Sharp/blob/master/mesh_ops/MeshIsoCurves.cs#L167) class, this line:
`                       
int graph_eid = Graph.AppendEdge(e0, e1, (int)TriangleCase.OnEdge);

if (WantGraphEdgeInfo)
   add_on_edge(graph_eid, tid, triEdges[z0], new Index2i(e0, e1));
`

when AppendEdge returns -1, that is DuplicateEdgeID, then next method crashes. Upgrading condition to
`
if (WantGraphEdgeInfo && graph_eid >= 0)
`
solves this issue but I'm not 100% positive if this is the right way hence no PR, only issue.

**Comment by rms80** [comment]
is there any way you can send me the stl? if you don't want to post here you could email it to rms@gradientspace.com. Clearly the check you mentioned be there but this possibly is an instance of a larger problem...

**Comment by benetnash** [comment]
Sure thing, I wasn't sure what's max attachment size hence I didn't add it before. It seems stl zips nicely anyway. 
[Slim_Type1.zip](https://github.com/gradientspace/geometry3Sharp/files/1862780/Slim_Type1.zip)

This is some free stl found online, problem can be reproduced with MeshToGCodeDemo, replace cylinder with:
`
            mesh = StandardMeshReader.ReadMesh("Slim_Type1.stl");
`

**Comment by rms80** [comment]
your fix was the best we can do in this case. just checked in.

Losing these duplicate edges does mean that some closed iso-loops might not be found. But the graph class doesn't support having multiple edges between the same vertices, so handling that case requires a lot of changes elsewhere.
