### ISSUE TITLE
How to add this project into Unity3D

### ISSUE THREAD

**Issue by shugraphics** [gradientspace/geometry3Sharp#48]
I want to apply this project to make Mesh of 3D hands model in Unity, for VR .After I try to do it,it seems that those codes are not the whole project for Unity ,so I would like to know how to do with it.
 one graduate from Shanghai University ,China

**Comment by shugraphics** [comment]
If you share some movie about applying  this project  ,I will sincerely appreciate it.

**Comment by rms80** [comment]
Sorry, you will have to do some background reading to learn more about what you are trying to do. These are questions about very basic things, and are going to lead to many more questions. I can't provide the level of help you are asking for, not for free.

You can try the sample unity project in https://github.com/gradientspace/geometry3UnityDemos , but I am not going to answer questions about that, either.

**Comment by shugraphics** [comment]
thank you,I am so sorry that I am layman .yesterday ,I have found that project ,and successfully run it ,but I can't see the result of "Mesh Simplification with g3Sharp". After I seriously study it ,I  consult you if I have any question.
