### ISSUE TITLE
How to calculate intersecting length   

### ISSUE THREAD

**Issue by rajxabc** [gradientspace/geometry3Sharp#52]
Is it possible to calculate length of intersecting line(ray) segment with a mesh volume. 
(In picture, total traversing length [green in color] )
Thanks

![torussegmentintersectionsml2](https://user-images.githubusercontent.com/40023139/41090514-67699d18-6a7f-11e8-8939-1c85a30f9851.jpg)

**Comment by rms80** [comment]
DMeshAABBTree.FindAllHitTriangles() will find all the hit triangles. Pass each triangle ID into MeshQueries. TriangleIntersection() to get the intersection objects. Sort by ray parameter. Then you have ray T values [t0,t1,t2,t3,t4,...]

if your objects are clean closed manifold meshes w/ no self-intersections, then you can just sequentially pair sequential t's - ie the spans are [t0,t1], [t2,t3], etc. Add up widths of these intervals.

If your objects are not nice closed solids, things get...complicated =).

**Comment by rajxabc** [comment]
And i have to check for vertex edges and planes And normals for in_out in code ?

**Comment by rms80** [comment]
yes, if you want to handle edge/plane intersections then things also get more complicated. The intersection object returned by MeshQueries.TriangleIntersection() returns flags that indicate these cases. 

if your rays are always starting outside the object, and the object is a closed non-self-intersecting mesh, then you don't need to do the normal checking, you can just pair the intervals. In all other cases yes you need to do some kind of hack like that.

An alternative that is more robust but less precise would be to densely sample the mesh winding number along the ray (the AABBTree class has a function for this). The value is 0 outside and non-zero inside. This works w/ self-intersections. If you want precision you can do a bisection rootfinding at each zero/nonzero crossing.

**Comment by rms80** [comment]
also you should know that the current AABB ray-intersection is not strictly water-tight, so rays can sometimes sneak between two coincident edges, or hit two triangles on their shared edge, depending on the numerics. To work around this you could jitter the ray and combine multiple samples.

**Comment by rajxabc** [comment]
I see, thank you Ryan.
Have a nice day
