### ISSUE TITLE
Is there method to process this kind of mesh?

### ISSUE THREAD

**Issue by samyuchao** [gradientspace/geometry3Sharp#55]
How to preserve the boundary shape and uniform the triangles.
![image](https://user-images.githubusercontent.com/10825626/42279438-5a38b8d4-7fd0-11e8-96b9-3b32a0dc3556.png)

**Comment by rms80** [comment]
Yes. I wrote a tutorial: http://www.gradientspace.com/tutorials/2018/7/5/remeshing-and-constraints

**Comment by samyuchao** [comment]
Woow, cool.

**Comment by samyuchao** [comment]
I just found we were colleagues at autodesk in 2011...Amazing!  Linkin...
