### ISSUE TITLE
OBJ Group Name Missing

### ISSUE THREAD

**Issue by SephirothJenova** [gradientspace/geometry3Sharp#57]
I found that you were using the g-tag for merge only, and I can not found the group names of different faces when I need them. It's kind of horrible when I can only distinguish these groups by int. So how can I do?

**Comment by rms80** [comment]
OBJReader.ParseInput() builds a Dictionary<string,int> called GroupNames that maps the strings to the ints. Currently this is local to the function but you could easily make it a class member if you want access after the read completes. You would have to construct the reverse map to get back to the names from the ints.

(Feel free to submit a PR if you do this)

However, DMesh3 does not support attaching a string group-name to each triangle, that would be insane. If you want to keep track of your group names across operations you will have to manage this yourself.

**Comment by SephirothJenova** [comment]
Thanks a lot. Help a lot.
