### ISSUE TITLE
How to use Curve3Curve3RevolveGenerator?

### ISSUE THREAD

**Issue by JSandusky** [gradientspace/geometry3Sharp#68]
I can't quite figure out what this is for or how to use it.

At first I assumed it was a loft but I can't gather how it could work for a loft. Is this just a revolve but per-slice orientation?

Since I couldn't figure it out I rolled this to do a loft:

        public class Curve3LoftGenerator : MeshGenerator
        {
            /// <summary>
            /// 2d cross-section of the geometry to emit
            /// </summary>
            public Vector2d[] Profile;
            /// <summary>
            /// Points where the profile should be executed
            /// </summary>
            public Vector3d[] Corners;
            /// <summary>
            /// Vector along which to extend the profile's X coordinate
            /// </summary>
            public Vector3d[] CornerNormals;
            
            public override MeshGenerator Generate()
            {
                int slices = Profile.Length - 1;
                int edges = Corners.Length - 1;
                vertices = new VectorArray3d(Profile.Length * Corners.Length);
                uv = new VectorArray2f(Profile.Length * Corners.Length);
                triangles = new IndexArray3i((edges) * (2 * slices));
                int vertIdx = 0;
                for (int u = 0; u < edges+1; ++u)
                {
                    float uCoord = (u / (float)(edges));
                    Vector3d cornerNorm = CornerNormals[u];
                    Vector3d cornerPt = Corners[u];
                    for (int v = 0; v < slices+1; ++v)
                    {
                        float vCoord = (v / (float)(slices));
                        Vector2d profPt = Profile[v];
                        Vector3d pt = cornerPt;
                        pt.y += profPt.y;
                        pt += cornerNorm * profPt.x;
                        System.Diagnostics.Debug.Assert(!double.IsNaN(pt.x));
                        System.Diagnostics.Debug.Assert(!double.IsNaN(pt.y));
                        System.Diagnostics.Debug.Assert(!double.IsNaN(pt.z));
                        vertices[vertIdx] = pt;
                        uv[vertIdx] = new Vector2f(uCoord, vCoord);
                        ++vertIdx;
                    }
                }
                int vv = 0;
                int ti = 0;
                for (int stack = 0; stack < edges; stack++)
                {
                    for (int slice = 0; slice < slices; slice++)
                    {
                        int next = slice + 1;
                        int faceA = vv + slice + slices + 1;
                        int faceB = vv + next;
                        int faceC = vv + slice;
                        int faceD = vv + slice + slices + 1;
                        int faceE = vv + next + slices + 1;
                        int faceF = vv + next;
                        triangles.Set(ti++, faceA, faceB, faceC);
                        triangles.Set(ti++, faceD, faceE, faceF);
                    }
                    vv += slices + 1;
                }
                return this;
            }
        }

**Comment by rms80** [comment]
it is definitely not a Loft. It's something like section 4.1 from this paper: http://www.inesc-id.pt/ficheiros/publicacoes/2502.pdf, so roughly yes a revolve but with the plane-of-revolution varying at each point along the Revolve curve, based on the Axis curve.

There is a brief example in this video, I use it to model the body solid: https://www.youtube.com/watch?v=0PtXAfWaZ3g   (although the Axis curve is nearly a straight line in this case, so the effect is minimal).

**Comment by JSandusky** [comment]
Thanks! That gives me enough that I can figure out how to use it.

Will you take a lofting PR (that's more robust than the strip only thing I whipped together)?

**Comment by rms80** [comment]
yes I would take a lofting PR. If you don't end up implementing a completely general loft, that's fine, just try to give it a more descriptive name.
