### ISSUE TITLE
FastWindingNumber Bug

### ISSUE THREAD

**Issue by ruribev** [gradientspace/geometry3Sharp#72]
Hello!

I tried to implement the FastWindingNumber on Vb.net and keep getting the following error:

    Class PWNImplicit : Implements g3.BoundedImplicitFunction3d

        Public Spatial As g3.PointAABBTree3

        Public Function Bounds() As g3.AxisAlignedBox3d Implements g3.BoundedImplicitFunction3d.Bounds
            Return Spatial.Bounds
        End Function
        Public Function Value(ByRef pt As g3.Vector3d) As Double Implements g3.ImplicitFunction3d.Value
            Return -(Spatial.FastWindingNumber(pt) - 0.5)
        End Function

    End Class

This is the other code:

        Dim gen As g3.Sphere3Generator_NormalizedCube = New g3.Sphere3Generator_NormalizedCube() With {
                    .EdgeVertices = 20
                }

        Dim mesht As g3.DMesh3 = gen.Generate().MakeDMesh()
        g3.MeshNormals.QuickCompute(mesht)
        Dim pointBVTree As g3.PointAABBTree3 = New g3.PointAABBTree3(mesht, True)

        Dim mine, maxe, avge As Double
        g3.MeshQueries.EdgeLengthStats(mesht, mine, maxe, avge)
        Dim circ As g3.Circle2d = New g3.Circle2d(g3.Vector2d.Zero, avge * 0.5)
        Dim vtxArea As Double = circ.Area

        pointBVTree.FWNAreaEstimateF = Function(vid) vtxArea

        Dim mc As g3.MarchingCubes = New g3.MarchingCubes()
        Dim Implicit = New PWNImplicit()
        Implicit.Spatial = pointBVTree
        Implicit.Bounds()
        mc.Implicit = Implicit

        mc.IsoValue = 0.0
        mc.CubeSize = pointBVTree.Bounds.MaxDim / 12.8
        mc.Bounds = pointBVTree.Bounds.Expanded(mc.CubeSize * 3)
        mc.RootMode = g3.MarchingCubes.RootfindingModes.Bisection
        mc.Generate()
        Dim resultMesh As g3.DMesh3 = mc.Mesh

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: The destination matrix is ​not long enough. Check destIndex, the length and the lower limits of the matrix.

   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at g3.PointAABBTree3.make_box_fast_winding_cache(Int32 iBox, IEnumerable`1 pointIndices)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache()
   at g3.PointAABBTree3.FastWindingNumber(Vector3d p)
   at Geomine.Create.PWNImplicit.Value(Vector3d& pt) in G:\DOCUMENTOS\MISDOC\Visual Studio 2015\Projects\Acad VB test2\Acad VB test\CADObjects\Create.vb:line 38
   at g3.MarchingCubes.initialize_cell(GridCell cell, Vector3i& idx)
   at g3.MarchingCubes.<generate_parallel>b__21_0(Int32 zi)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at g3.MarchingCubes.generate_parallel()
   at Geomine.Create.solidCavity(List`1 dbm, Int32 de, Int32 hasta, Double filter) in G:\DOCUMENTOS\MISDOC\Visual Studio 2015\Projects\Acad VB test2\Acad VB test\CADObjects\Create.vb:line 74
   at Geomine.MeshBuilder_Form.CreateSolids_Click(Object sender, EventArgs e) in G:\DOCUMENTOS\MISDOC\Visual Studio 2015\Projects\Acad VB test2\Acad VB test\ModCADTools\Mesh\MeshBuilder_Form.vb:line 87
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.ArgumentException: La matriz de destino no es suficientemente larga. Compruebe destIndex, la longitud y los límites inferiores de la matriz.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at g3.PointAABBTree3.make_box_fast_winding_cache(Int32 iBox, IEnumerable`1 pointIndices)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache(Int32 iBox, Int32 depth, Int32 pt_count_thresh, HashSet`1& pts_hash)
   at g3.PointAABBTree3.build_fast_winding_cache()
   at g3.PointAABBTree3.FastWindingNumber(Vector3d p)
   at Geomine.Create.PWNImplicit.Value(Vector3d& pt) in G:\DOCUMENTOS\MISDOC\Visual Studio 2015\Projects\Acad VB test2\Acad VB test\CADObjects\Create.vb:line 38
   at g3.MarchingCubes.initialize_cell(GridCell cell, Vector3i& idx)
   at g3.MarchingCubes.<generate_parallel>b__21_0(Int32 zi)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Acdbmgd
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AcdbMgd.DLL
----------------------------------------
adui21
    Assembly Version: 0.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/adui21.DLL
----------------------------------------
AdUiPalettes
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AdUiPalettes.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
WpfXamlDiagnosticsTap
    Assembly Version: 14.0.0.0
    Win32 Version: 14.0.25431.1
    CodeBase: file:///C:/Users/Rodrigo/AppData/Local/Temp/VisualStudio.XamlDiagnostics.1493204/WpfXamlDiagnosticsTap.dll
----------------------------------------
Microsoft.VisualStudio.OLE.Interop
    Assembly Version: 7.1.40304.0
    Win32 Version: 7.10.6070
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.VisualStudio.OLE.Interop/7.1.40304.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.OLE.Interop.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AdApplicationFrame
    Assembly Version: 0.0.0.0
    Win32 Version: 2015.11.1.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AdApplicationFrame.DLL
----------------------------------------
AdWindows
    Assembly Version: 2015.11.2.0
    Win32 Version: 2015.11.2.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AdWindows.DLL
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
accoremgd
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/accoremgd.DLL
----------------------------------------
Acmgd
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/Acmgd.DLL
----------------------------------------
AcWindows
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AcWindows.DLL
----------------------------------------
AcWindows.resources
    Assembly Version: 0.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/en-US/AcWindows.resources.DLL
----------------------------------------
AcCui
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AcCui.DLL
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationFramework.Aero
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
----------------------------------------
PresentationUI
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationUI/v4.0_4.0.0.0__31bf3856ad364e35/PresentationUI.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
BIM360GlueAutoCAD2017Addin
    Assembly Version: 4.37.6853.0
    Win32 Version: 4.37.6853.0
    CodeBase: file:///C:/ProgramData/Autodesk/ApplicationPlugins/AutoCAD2017Addin.bundle/Contents/Win64/BIM360GlueAutoCAD2017Addin.dll
----------------------------------------
BIM360GlueAddinsCommon
    Assembly Version: 4.37.6853.0
    Win32 Version: 4.37.6853.0
    CodeBase: file:///C:/ProgramData/Autodesk/ApplicationPlugins/AutoCAD2017Addin.bundle/Contents/Win64/BIM360GlueAddinsCommon.DLL
----------------------------------------
log4net
    Assembly Version: 1.2.11.0
    Win32 Version: 1.2.11.0
    CodeBase: file:///C:/ProgramData/Autodesk/ApplicationPlugins/AutoCAD2017Addin.bundle/Contents/Win64/log4net.DLL
----------------------------------------
FeaturedAppsPlugin
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.46.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Autodesk/ApplicationPlugins/Autodesk%20FeaturedApps.bundle/Contents/Windows/2017/Win64/FeaturedAppsPlugin.dll
----------------------------------------
Geomine
    Assembly Version: 1.0.1.50
    Win32 Version: 1.0.1.50
    CodeBase: file:///C:/Geomine/Bin/Geomine.dll
----------------------------------------
MIConvexHull
    Assembly Version: 1.0.10.1021
    Win32 Version: 1.0.10.1021
    CodeBase: file:///C:/Geomine/Bin/MIConvexHull.DLL
----------------------------------------
geometry3Sharp
    Assembly Version: 1.0.289.0
    Win32 Version: 1.0.289.0
    CodeBase: file:///C:/Geomine/Bin/geometry3Sharp.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
ContextualTabSelectorRules
    Assembly Version: 0.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AcWindows.dll
----------------------------------------
Microsoft.Expression.Interactions
    Assembly Version: 4.0.0.0
    Win32 Version: 2.0.20520.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/Microsoft.Expression.Interactions.DLL
----------------------------------------
PresentationFramework-SystemCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll
----------------------------------------
KDTree
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Geomine/Bin/KDTree.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Windows.UI
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.UI.winmd
----------------------------------------
System.Runtime.InteropServices.WindowsRuntime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.WindowsRuntime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.WindowsRuntime.dll
----------------------------------------
ClicJsInfoCenter
    Assembly Version: 0.0.0.0
    Win32 Version: 3.1.26.0
    CodeBase: file:///C:/Program%20Files/Common%20Files/Autodesk%20Shared/CLM/V3/MSVC14/ClicJsInfoCenter.dll
----------------------------------------
AcLivePreviewContext
    Assembly Version: 0.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AcWindows.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
AcLayer
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AcLayer.DLL
----------------------------------------
AcLayer.resources
    Assembly Version: 0.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/en-US/AcLayer.resources.DLL
----------------------------------------
AcCustomize
    Assembly Version: 21.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/AcCustomize.DLL
----------------------------------------
AcCustomize.resources
    Assembly Version: 0.0.0.0
    Win32 Version: 21.0.52.0.0
    CodeBase: file:///C:/Program%20Files/Autodesk/AutoCAD%202017/en-US/AcCustomize.resources.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
PresentationFramework.Luna
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Luna/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Luna.dll
----------------------------------------
mscorlib.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT Debugging **************
Application does not support Windows Forms just-in-time (JIT)
debugging. Contact the application author for more
information.

Let me know if you need anything else I can help with

**Comment by rms80** [comment]
You have not done an initial evaluation of the bvtree fast-winding number, from what I can see. Try calling bvtree.FastWindingNumber(Vector3d.Zero) before you run the marching cubes.

**Comment by ruribev** [comment]
Work like a charm! Thank you!
