### ISSUE TITLE
Mesh boolean operation

### ISSUE THREAD

**Issue by EnvyKong** [gradientspace/geometry3Sharp#77]
The data structure of DMesh3 is very excellent. 
Thank you very much!
This library is very powerful!
Why is there no Mesh Boolean operation? I have tried using SDF, but it is very expensive and easy to get wrong. 
I know from your twitter that you have tried to do something about Mesh Boolean.
Why doesn't this library have Mesh Boolean functionality yet.
Any questions?
Looking forward to your reply! Thank you!

**Comment by Evil-Spirit** [comment]
I also looking for robust boolean operations.

**Comment by rms80** [comment]
Robust mesh booleans are very difficult to implement. At minimum, arbitrary-precision rationals are required to precisely solve triangle-triangle intersections, and constrained delaunay triangulation. g3Sharp doesn't have either of these, and arbitrary-precision rationals would likely be quite slow in C#. 

The examples I posted on twitter were early experiments on very easy cases. This boolean is not close to working reliably or efficiently yet, sorry.

**Comment by EnvyKong** [comment]
Thank you very much! I will implement robust mesh booleans by an open source library called cork.
