### ISSUE TITLE
Are triangle groups the same as submeshes?

### ISSUE THREAD

**Issue by amirebrahimi** [gradientspace/geometry3Sharp#82]
I'm trying to support mesh reduction with separate submeshes and not sure that the triangle groups are what I think they are.

**Comment by amirebrahimi** [comment]
https://github.com/Unity-Technologies/AutoLOD/blob/f27a27bd96a39443b540bcf2f564eef757ff2a4a/Scripts/Editor/MeshSimplifiers/Geometry3SharpSimplifier.cs#L50

**Comment by rms80** [comment]
triangle groups are just per-triangle integers, they don't have any inherent semantics. They are ignored by the Reducer. Not sure what you mean by a "submesh" - if you mean Unity submesh, g3Sharp does not have that concept.
