### ISSUE TITLE
About display and interaction

### ISSUE THREAD

**Issue by EnvyKong** [gradientspace/geometry3Sharp#83]
Hello,
I'm trying to make a WPF  application with g3. I don't want to use Unity, it's too complex to me. I've tried vtk and opencascade. They're not very good. Do you have any components or anything recommend to me about display and interaction?

Thank you very much!

**Comment by rms80** [comment]
sorry, if you want to make a C# desktop app, you don't have a lot of options. I have frame3Sharp which is a higher-level CAD-framework but it is built on Unity: https://github.com/gradientspace/frame3SharpSampleApp

**Comment by EnvyKong** [comment]
Thanks! I also want to know what is the display engine of the MeshMixer and Cotangent. They are two excellent pieces of software. How do they implement interface interactions?

Looking forward to your reply!

**Comment by EnvyKong** [comment]
Awsome! Thank you very much! Now I will implement 3D interaction capabilities by vtk to built my desktop application confidently!
