### ISSUE TITLE
how to auto repair mesh ?  delete the isolated point triangles faces or duplicated data

### ISSUE THREAD

**Issue by dragonpoint** [gradientspace/geometry3Sharp#89]
Is there a way to auto repair a mesh loaded from .obj file?  delete the isolated point triangles faces or duplicated data

I use photoscan to make a 3d model from many pictures and export to a .obj file.  I load the obj file with c++ open mesh.  I found that the faces loaded by open mesh  maybe wrong because there are multiple triangles mapped to the same texture2d coordinate.  that is unreasonable!  the  triangles are not connected and not  neighbor to each other

**Comment by dragonpoint** [comment]
multiple mesh triangles mapped to the same texture 2d triangle

**Comment by rms80** [comment]
Sorry, g3Sharp does not really handle UVs. You would have to write the algorithm to do this yourself. Also how to "repair" it is unclear because where are you going to have those triangles map to instead? Or do you just want to delete them?

**Comment by dragonpoint** [comment]
thanks
