### ISSUE TITLE
Visualization for mesh in WPF

### ISSUE THREAD

**Issue by Rokeo** [gradientspace/geometry3Sharp#97]
Can you please suggest visualization library for mesh generated using your tool?

I saw it have Bitmap3, but didn't found how to convert this to normal image to show in WPF.

Thank you!

**Comment by rms80** [comment]
the simplest thing to do would be to export an OBJ and open that in something like Meshmixer. If you want to show it in a WPF form you need a renderer, there are OpenGL .NET libraries but I am not sure what works these days.

Bitmap3 is a 3D voxel grid, this will not help you.
